services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173