services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173